<?php
// $ID$

/**
 * @file
 *  Updates the calendar From below and to the Left when an event 
 *  is added or updated.
 *
 * ...
 */

function calupdate_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
    switch ($op) {
        case 'insert':
        case 'update':
            if ($node->type == 'cal_event') {
		$output = `php -f ~/calendar.redwoodcurtaincopwatch.net/update/update.php`;
	    }
	    break;
    }
}
